### ISSUE TITLE
`JSONDecodable` with static `parse` method?

### ISSUE THREAD

**Issue by bejar37** [matthewcheok/JSONCodable#66]
Hi,
Right now the definition for `JSONDecodable` requires an implementation of an initializer. This has a couple of drawbacks IMO:
* Enums with associated values can't conform to `JSONDecodable` (see #29)
* For classes, `JSONDecodable` has to be conformed to in the main class declaration, not in an extension. This means that classes defined in ObjC can't conform to `JSONDecodable` in a Swift extension, for example. 

My question is: what are opinions on a breaking change to moving to a definition of `JSONDecodable` that looks like this:

```swift
protocol JSONDecodable {
    static func parse(decoder: JSONDecoder) throws -> Self
}
```

I know that this would be a breaking change, but are there other reasons why this is a bad idea?

**Comment by Nadohs** [comment]
We thought about the impact of doing this awhile ago and the biggest reason we didn't like it was because this would require your class object properties to have all default values or another initializer defined in the class definition anyways to handle all the properties from the object.

Beyond that if you settle for one of those two conditions I believe you wouldn't necessarily require breaking changes. I played around with an implementation targeting objects using a new protocol `JSONObjectDecodable`, which is conformant to the original `JSONDecodable`.  Here is an implementation I threw together.

This is what it looks like in the extension for a class:
```
class NameCount {
    let name: String
    let count: Int
    init(name: String, count: Int) {
        self.name = name
        self.count = count
    }
}

extension NameCount: JSONObjectDecodable {

    static func construct(from object: JSONObject) throws -> Self {
        let decoder = JSONDecoder(object: object)

        let result = NameCount(name: try decoder.decode("name"),
                               count: try decoder.decode("count"))

        return DecodableCastAs(object: result)
    }
}
```

This is what the implementation to make this work looks like:
```

public protocol JSONObjectDecodable: JSONDecodable {
    static func construct(from object: JSONObject) throws -> Self
}

extension JSONObjectDecodable where Self: AnyObject {
    public init(object: JSONObject) throws {
        self = try Self.construct(from: object)
    }
}

// this is to avoid the class requiring to be marked `final` 
public func DecodableCastAs<T>(object: Any) -> T {
    return object as! T
}
```

Here is a branch with this implementation along with one test for this implementation: 
https://github.com/matthewcheok/JSONCodable/tree/object-constructor

**Comment by matthewcheok** [comment]
For a workaround for enums, we can always provide a JSONTransformer at the parent level.

The main trade-offs for proceeding is as @Nadohs mentioned:
- Allow conforming to JSONCodable via class extensions (+)
- Introducing more boilerplate for classes (-)

I think it might be worth considering if there's more to gain but at this moment it doesn't seem like a sufficient reason for introducing a breaking change.

**Comment by bejar37** [comment]
Ah, ok. Thanks for the quick response! Most of my models are structs or enums and not classes so I hadn't thought much about the boilerplate issue.

To me, structs and classes sort of fill similar niches, and by default I choose structs over classes when modeling my data. My project currently only uses model classes when the model is defined in Objective C, and in that case I can't use `JSONDecodable` at all. On the other hand enums with associated values are one of the best features in swift, I can't seem to find a swift library that has really great support for it.

I know that it's possible to use `JSONTransormer`, but for some of the models I'm parsing I want to be able to use a `JSONDecoder` (see #67).

Either way, this is a really nice project and I've taken a lot of inspiration from it! Keep up the great work :).

**Comment by bejar37** [comment]
To give some more context, last week a code generation library, [Sourcery](https://github.com/krzysztofzablocki/Sourcery) was released. I'm currently exploring tying `Sourcery` and `JSONCodable` together in a nice way!
