### ISSUE TITLE
How to decode a root-level JSON array?

### ISSUE THREAD

**Issue by tonyarnold** [matthewcheok/JSONCodable#8]
Is there any way to do this with the current release? I see that the JSONDecodable protocol declares a convenience init method for dictionaries, but what about for APIs that return an array as their root?

**Comment by matthewcheok** [comment]
TLDR: I couldn't find a type safe way to do it.

Not right now there isn't. The single model init method is obvious because the return type is well a single model. For the array version, I was thinking about extending an initializer for `Array` but it didn't make sense to extend all arrays maybe just those which `Element` matches the corresponding type. 

If you've got any ideas, do share!

**Comment by matthewcheok** [comment]
Just realised I had a implementation of the array initialiser all along:

```
let friends = [User](JSONArray: [
            ["id": 27, "full_name": "Bob Jefferson"],
            ["id": 29, "full_name": "Jen Jackson"]
            ])
```

**Comment by tonyarnold** [comment]
Great, works a treat — thanks @matthewcheok!
